#Introduction to Tensorflow

In [ ]:
import tensorflow as tf

##Creation

In [ ]:
str=tf.Variable("String",tf.string)
num=tf.Variable(123,tf.int32)
flt=tf.Variable(1.23,tf.float32)

##Rank/Degree

In [ ]:
r1=tf.Variable(["one","two","three"],tf.string)
r2=tf.Variable([["one","two","one"],["three","four","four"]],tf.string)

In [ ]:
tf.rank(r1)


<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [ ]:
tf.rank(r2)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

##Shape

In [ ]:
tf.shape(r1)

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([3], dtype=int32)>

In [ ]:
tf.shape(r2)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>

In [ ]:
arr=tf.ones([2,3])
tf.reshape(arr,[3,2])
print(arr)
tf.reshape(arr,[3,-1])

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

##Types of tensors
Variable,
Constant,
Placeholder,
SparseTensor,